#!/bin/bash

function saptdater(){
  sudo clear; echo "\n[+] [                    ] -> UPDATING SYSTEM TOOLS [+]\r"
  sudo apt update -y &>/dev/null && clear; echo "\n[+] [//                  ] -> UPDATING SYSTEM TOOLS [+]\r"
  sudo apt full-upgrade -y &>/dev/null && clear; echo "\n[+] [////                ] -> UPDATING SYSTEM TOOLS [+]\r"
  sudo apt autoremove -y &>/dev/null && clear; echo "\n[+] [//////              ] -> UPDATING SYSTEM TOOLS [+]\r"
  sudo apt-get update -y &>/dev/null && clear; echo "\n[+] [////////            ] -> UPDATING SYSTEM TOOLS [+]\r"
  sudo apt-get full-upgrade -y &>/dev/null && clear; echo "\n[+] [//////////          ] -> UPDATING SYSTEM TOOLS [+]\r"
  sudo apt-get autoremove -y &>/dev/null && clear; echo "\n[+] [////////////        ] -> UPDATING THE SYSTEM [+]\r"
  sudo apt dist-upgrade -y &>/dev/null && clear; echo "\n[+] [//////////////      ] -> UPDATING THE SYSTEM [+]\r"
  sudo parrot-upgrade --fix-missing -y &>/dev/null && clear; echo "\n[+] [////////////////    ] -> UPDATING THE TOOLS DATABASES [+]\n"
  sudo nmap --script-updatedb &>/dev/null && clear; echo "\n[+] [//////////////////  ] -> UPDATING THE TOOLS DATABASES [+]\n"
  sudo searchsploit -u &>/dev/null
  clear; echo "\n[+] [////////////////////] => UPDATE SUCCESSFULLY COMPLETED [+]\n"
}
